# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/struct_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("schema.proto", :syntax => :proto3) do
    add_message "immudb.schema.Key" do
      optional :key, :bytes, 1
    end
    add_message "immudb.schema.Permission" do
      optional :database, :string, 1
      optional :permission, :uint32, 2
    end
    add_message "immudb.schema.User" do
      optional :user, :bytes, 1
      repeated :permissions, :message, 3, "immudb.schema.Permission"
      optional :createdby, :string, 4
      optional :createdat, :string, 5
      optional :active, :bool, 6
    end
    add_message "immudb.schema.UserList" do
      repeated :users, :message, 1, "immudb.schema.User"
    end
    add_message "immudb.schema.CreateUserRequest" do
      optional :user, :bytes, 1
      optional :password, :bytes, 2
      optional :permission, :uint32, 3
      optional :database, :string, 4
    end
    add_message "immudb.schema.UserRequest" do
      optional :user, :bytes, 1
    end
    add_message "immudb.schema.ChangePasswordRequest" do
      optional :user, :bytes, 1
      optional :oldPassword, :bytes, 2
      optional :newPassword, :bytes, 3
    end
    add_message "immudb.schema.LoginRequest" do
      optional :user, :bytes, 1
      optional :password, :bytes, 2
    end
    add_message "immudb.schema.LoginResponse" do
      optional :token, :string, 1
      optional :warning, :bytes, 2
    end
    add_message "immudb.schema.AuthConfig" do
      optional :kind, :uint32, 1
    end
    add_message "immudb.schema.MTLSConfig" do
      optional :enabled, :bool, 1
    end
    add_message "immudb.schema.OpenSessionRequest" do
      optional :username, :bytes, 1
      optional :password, :bytes, 2
      optional :databaseName, :string, 3
    end
    add_message "immudb.schema.OpenSessionResponse" do
      optional :sessionID, :string, 1
      optional :serverUUID, :string, 2
    end
    add_message "immudb.schema.Precondition" do
      oneof :precondition do
        optional :keyMustExist, :message, 1, "immudb.schema.Precondition.KeyMustExistPrecondition"
        optional :keyMustNotExist, :message, 2, "immudb.schema.Precondition.KeyMustNotExistPrecondition"
        optional :keyNotModifiedAfterTX, :message, 3, "immudb.schema.Precondition.KeyNotModifiedAfterTXPrecondition"
      end
    end
    add_message "immudb.schema.Precondition.KeyMustExistPrecondition" do
      optional :key, :bytes, 1
    end
    add_message "immudb.schema.Precondition.KeyMustNotExistPrecondition" do
      optional :key, :bytes, 1
    end
    add_message "immudb.schema.Precondition.KeyNotModifiedAfterTXPrecondition" do
      optional :key, :bytes, 1
      optional :txID, :uint64, 2
    end
    add_message "immudb.schema.KeyValue" do
      optional :key, :bytes, 1
      optional :value, :bytes, 2
      optional :metadata, :message, 3, "immudb.schema.KVMetadata"
    end
    add_message "immudb.schema.Entry" do
      optional :tx, :uint64, 1
      optional :key, :bytes, 2
      optional :value, :bytes, 3
      optional :referencedBy, :message, 4, "immudb.schema.Reference"
      optional :metadata, :message, 5, "immudb.schema.KVMetadata"
      optional :expired, :bool, 6
      optional :revision, :uint64, 7
    end
    add_message "immudb.schema.Reference" do
      optional :tx, :uint64, 1
      optional :key, :bytes, 2
      optional :atTx, :uint64, 3
      optional :metadata, :message, 4, "immudb.schema.KVMetadata"
      optional :revision, :uint64, 5
    end
    add_message "immudb.schema.Op" do
      oneof :operation do
        optional :kv, :message, 1, "immudb.schema.KeyValue"
        optional :zAdd, :message, 2, "immudb.schema.ZAddRequest"
        optional :ref, :message, 3, "immudb.schema.ReferenceRequest"
      end
    end
    add_message "immudb.schema.ExecAllRequest" do
      repeated :Operations, :message, 1, "immudb.schema.Op"
      optional :noWait, :bool, 2
      repeated :preconditions, :message, 3, "immudb.schema.Precondition"
    end
    add_message "immudb.schema.Entries" do
      repeated :entries, :message, 1, "immudb.schema.Entry"
    end
    add_message "immudb.schema.ZEntry" do
      optional :set, :bytes, 1
      optional :key, :bytes, 2
      optional :entry, :message, 3, "immudb.schema.Entry"
      optional :score, :double, 4
      optional :atTx, :uint64, 5
    end
    add_message "immudb.schema.ZEntries" do
      repeated :entries, :message, 1, "immudb.schema.ZEntry"
    end
    add_message "immudb.schema.ScanRequest" do
      optional :seekKey, :bytes, 1
      optional :prefix, :bytes, 2
      optional :desc, :bool, 3
      optional :limit, :uint64, 4
      optional :sinceTx, :uint64, 5
      optional :noWait, :bool, 6
    end
    add_message "immudb.schema.KeyPrefix" do
      optional :prefix, :bytes, 1
    end
    add_message "immudb.schema.EntryCount" do
      optional :count, :uint64, 1
    end
    add_message "immudb.schema.Signature" do
      optional :publicKey, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "immudb.schema.TxHeader" do
      optional :id, :uint64, 1
      optional :prevAlh, :bytes, 2
      optional :ts, :int64, 3
      optional :nentries, :int32, 4
      optional :eH, :bytes, 5
      optional :blTxId, :uint64, 6
      optional :blRoot, :bytes, 7
      optional :version, :int32, 8
      optional :metadata, :message, 9, "immudb.schema.TxMetadata"
    end
    add_message "immudb.schema.TxMetadata" do
    end
    add_message "immudb.schema.LinearProof" do
      optional :sourceTxId, :uint64, 1
      optional :TargetTxId, :uint64, 2
      repeated :terms, :bytes, 3
    end
    add_message "immudb.schema.DualProof" do
      optional :sourceTxHeader, :message, 1, "immudb.schema.TxHeader"
      optional :targetTxHeader, :message, 2, "immudb.schema.TxHeader"
      repeated :inclusionProof, :bytes, 3
      repeated :consistencyProof, :bytes, 4
      optional :targetBlTxAlh, :bytes, 5
      repeated :lastInclusionProof, :bytes, 6
      optional :linearProof, :message, 7, "immudb.schema.LinearProof"
    end
    add_message "immudb.schema.Tx" do
      optional :header, :message, 1, "immudb.schema.TxHeader"
      repeated :entries, :message, 2, "immudb.schema.TxEntry"
      repeated :kvEntries, :message, 3, "immudb.schema.Entry"
      repeated :zEntries, :message, 4, "immudb.schema.ZEntry"
    end
    add_message "immudb.schema.TxEntry" do
      optional :key, :bytes, 1
      optional :hValue, :bytes, 2
      optional :vLen, :int32, 3
      optional :metadata, :message, 4, "immudb.schema.KVMetadata"
      optional :value, :bytes, 5
    end
    add_message "immudb.schema.KVMetadata" do
      optional :deleted, :bool, 1
      optional :expiration, :message, 2, "immudb.schema.Expiration"
      optional :nonIndexable, :bool, 3
    end
    add_message "immudb.schema.Expiration" do
      optional :expiresAt, :int64, 1
    end
    add_message "immudb.schema.VerifiableTx" do
      optional :tx, :message, 1, "immudb.schema.Tx"
      optional :dualProof, :message, 2, "immudb.schema.DualProof"
      optional :signature, :message, 3, "immudb.schema.Signature"
    end
    add_message "immudb.schema.VerifiableEntry" do
      optional :entry, :message, 1, "immudb.schema.Entry"
      optional :verifiableTx, :message, 2, "immudb.schema.VerifiableTx"
      optional :inclusionProof, :message, 3, "immudb.schema.InclusionProof"
    end
    add_message "immudb.schema.InclusionProof" do
      optional :leaf, :int32, 1
      optional :width, :int32, 2
      repeated :terms, :bytes, 3
    end
    add_message "immudb.schema.SetRequest" do
      repeated :KVs, :message, 1, "immudb.schema.KeyValue"
      optional :noWait, :bool, 2
      repeated :preconditions, :message, 3, "immudb.schema.Precondition"
    end
    add_message "immudb.schema.KeyRequest" do
      optional :key, :bytes, 1
      optional :atTx, :uint64, 2
      optional :sinceTx, :uint64, 3
      optional :noWait, :bool, 4
      optional :atRevision, :int64, 5
    end
    add_message "immudb.schema.KeyListRequest" do
      repeated :keys, :bytes, 1
      optional :sinceTx, :uint64, 2
    end
    add_message "immudb.schema.DeleteKeysRequest" do
      repeated :keys, :bytes, 1
      optional :sinceTx, :uint64, 2
      optional :noWait, :bool, 3
    end
    add_message "immudb.schema.VerifiableSetRequest" do
      optional :setRequest, :message, 1, "immudb.schema.SetRequest"
      optional :proveSinceTx, :uint64, 2
    end
    add_message "immudb.schema.VerifiableGetRequest" do
      optional :keyRequest, :message, 1, "immudb.schema.KeyRequest"
      optional :proveSinceTx, :uint64, 2
    end
    add_message "immudb.schema.HealthResponse" do
      optional :status, :bool, 1
      optional :version, :string, 2
    end
    add_message "immudb.schema.DatabaseHealthResponse" do
      optional :pendingRequests, :uint32, 1
      optional :lastRequestCompletedAt, :int64, 2
    end
    add_message "immudb.schema.ImmutableState" do
      optional :db, :string, 1
      optional :txId, :uint64, 2
      optional :txHash, :bytes, 3
      optional :signature, :message, 4, "immudb.schema.Signature"
    end
    add_message "immudb.schema.ReferenceRequest" do
      optional :key, :bytes, 1
      optional :referencedKey, :bytes, 2
      optional :atTx, :uint64, 3
      optional :boundRef, :bool, 4
      optional :noWait, :bool, 5
      repeated :preconditions, :message, 6, "immudb.schema.Precondition"
    end
    add_message "immudb.schema.VerifiableReferenceRequest" do
      optional :referenceRequest, :message, 1, "immudb.schema.ReferenceRequest"
      optional :proveSinceTx, :uint64, 2
    end
    add_message "immudb.schema.ZAddRequest" do
      optional :set, :bytes, 1
      optional :score, :double, 2
      optional :key, :bytes, 3
      optional :atTx, :uint64, 4
      optional :boundRef, :bool, 5
      optional :noWait, :bool, 6
    end
    add_message "immudb.schema.Score" do
      optional :score, :double, 1
    end
    add_message "immudb.schema.ZScanRequest" do
      optional :set, :bytes, 1
      optional :seekKey, :bytes, 2
      optional :seekScore, :double, 3
      optional :seekAtTx, :uint64, 4
      optional :inclusiveSeek, :bool, 5
      optional :limit, :uint64, 6
      optional :desc, :bool, 7
      optional :minScore, :message, 8, "immudb.schema.Score"
      optional :maxScore, :message, 9, "immudb.schema.Score"
      optional :sinceTx, :uint64, 10
      optional :noWait, :bool, 11
    end
    add_message "immudb.schema.HistoryRequest" do
      optional :key, :bytes, 1
      optional :offset, :uint64, 2
      optional :limit, :int32, 3
      optional :desc, :bool, 4
      optional :sinceTx, :uint64, 5
    end
    add_message "immudb.schema.VerifiableZAddRequest" do
      optional :zAddRequest, :message, 1, "immudb.schema.ZAddRequest"
      optional :proveSinceTx, :uint64, 2
    end
    add_message "immudb.schema.TxRequest" do
      optional :tx, :uint64, 1
      optional :entriesSpec, :message, 2, "immudb.schema.EntriesSpec"
      optional :sinceTx, :uint64, 3
      optional :noWait, :bool, 4
    end
    add_message "immudb.schema.EntriesSpec" do
      optional :kvEntriesSpec, :message, 1, "immudb.schema.EntryTypeSpec"
      optional :zEntriesSpec, :message, 2, "immudb.schema.EntryTypeSpec"
      optional :sqlEntriesSpec, :message, 3, "immudb.schema.EntryTypeSpec"
    end
    add_message "immudb.schema.EntryTypeSpec" do
      optional :action, :enum, 1, "immudb.schema.EntryTypeAction"
    end
    add_message "immudb.schema.VerifiableTxRequest" do
      optional :tx, :uint64, 1
      optional :proveSinceTx, :uint64, 2
      optional :entriesSpec, :message, 3, "immudb.schema.EntriesSpec"
      optional :sinceTx, :uint64, 4
      optional :noWait, :bool, 5
    end
    add_message "immudb.schema.TxScanRequest" do
      optional :initialTx, :uint64, 1
      optional :limit, :uint32, 2
      optional :desc, :bool, 3
      optional :entriesSpec, :message, 4, "immudb.schema.EntriesSpec"
      optional :sinceTx, :uint64, 5
      optional :noWait, :bool, 6
    end
    add_message "immudb.schema.TxList" do
      repeated :txs, :message, 1, "immudb.schema.Tx"
    end
    add_message "immudb.schema.ExportTxRequest" do
      optional :tx, :uint64, 1
    end
    add_message "immudb.schema.Database" do
      optional :databaseName, :string, 1
    end
    add_message "immudb.schema.DatabaseSettings" do
      optional :databaseName, :string, 1
      optional :replica, :bool, 2
      optional :masterDatabase, :string, 3
      optional :masterAddress, :string, 4
      optional :masterPort, :uint32, 5
      optional :followerUsername, :string, 6
      optional :followerPassword, :string, 7
      optional :fileSize, :uint32, 8
      optional :maxKeyLen, :uint32, 9
      optional :maxValueLen, :uint32, 10
      optional :maxTxEntries, :uint32, 11
      optional :excludeCommitTime, :bool, 12
    end
    add_message "immudb.schema.CreateDatabaseRequest" do
      optional :name, :string, 1
      optional :settings, :message, 2, "immudb.schema.DatabaseNullableSettings"
    end
    add_message "immudb.schema.CreateDatabaseResponse" do
      optional :name, :string, 1
      optional :settings, :message, 2, "immudb.schema.DatabaseNullableSettings"
    end
    add_message "immudb.schema.UpdateDatabaseRequest" do
      optional :database, :string, 1
      optional :settings, :message, 2, "immudb.schema.DatabaseNullableSettings"
    end
    add_message "immudb.schema.UpdateDatabaseResponse" do
      optional :database, :string, 1
      optional :settings, :message, 2, "immudb.schema.DatabaseNullableSettings"
    end
    add_message "immudb.schema.DatabaseSettingsRequest" do
    end
    add_message "immudb.schema.DatabaseSettingsResponse" do
      optional :database, :string, 1
      optional :settings, :message, 2, "immudb.schema.DatabaseNullableSettings"
    end
    add_message "immudb.schema.NullableUint32" do
      optional :value, :uint32, 1
    end
    add_message "immudb.schema.NullableUint64" do
      optional :value, :uint64, 1
    end
    add_message "immudb.schema.NullableFloat" do
      optional :value, :float, 1
    end
    add_message "immudb.schema.NullableBool" do
      optional :value, :bool, 1
    end
    add_message "immudb.schema.NullableString" do
      optional :value, :string, 1
    end
    add_message "immudb.schema.DatabaseNullableSettings" do
      optional :replicationSettings, :message, 2, "immudb.schema.ReplicationNullableSettings"
      optional :fileSize, :message, 8, "immudb.schema.NullableUint32"
      optional :maxKeyLen, :message, 9, "immudb.schema.NullableUint32"
      optional :maxValueLen, :message, 10, "immudb.schema.NullableUint32"
      optional :maxTxEntries, :message, 11, "immudb.schema.NullableUint32"
      optional :excludeCommitTime, :message, 12, "immudb.schema.NullableBool"
      optional :maxConcurrency, :message, 13, "immudb.schema.NullableUint32"
      optional :maxIOConcurrency, :message, 14, "immudb.schema.NullableUint32"
      optional :txLogCacheSize, :message, 15, "immudb.schema.NullableUint32"
      optional :vLogMaxOpenedFiles, :message, 16, "immudb.schema.NullableUint32"
      optional :txLogMaxOpenedFiles, :message, 17, "immudb.schema.NullableUint32"
      optional :commitLogMaxOpenedFiles, :message, 18, "immudb.schema.NullableUint32"
      optional :indexSettings, :message, 19, "immudb.schema.IndexNullableSettings"
      optional :writeTxHeaderVersion, :message, 20, "immudb.schema.NullableUint32"
      optional :autoload, :message, 21, "immudb.schema.NullableBool"
    end
    add_message "immudb.schema.ReplicationNullableSettings" do
      optional :replica, :message, 1, "immudb.schema.NullableBool"
      optional :masterDatabase, :message, 2, "immudb.schema.NullableString"
      optional :masterAddress, :message, 3, "immudb.schema.NullableString"
      optional :masterPort, :message, 4, "immudb.schema.NullableUint32"
      optional :followerUsername, :message, 5, "immudb.schema.NullableString"
      optional :followerPassword, :message, 6, "immudb.schema.NullableString"
    end
    add_message "immudb.schema.IndexNullableSettings" do
      optional :flushThreshold, :message, 1, "immudb.schema.NullableUint32"
      optional :syncThreshold, :message, 2, "immudb.schema.NullableUint32"
      optional :cacheSize, :message, 3, "immudb.schema.NullableUint32"
      optional :maxNodeSize, :message, 4, "immudb.schema.NullableUint32"
      optional :maxActiveSnapshots, :message, 5, "immudb.schema.NullableUint32"
      optional :renewSnapRootAfter, :message, 6, "immudb.schema.NullableUint64"
      optional :compactionThld, :message, 7, "immudb.schema.NullableUint32"
      optional :delayDuringCompaction, :message, 8, "immudb.schema.NullableUint32"
      optional :nodesLogMaxOpenedFiles, :message, 9, "immudb.schema.NullableUint32"
      optional :historyLogMaxOpenedFiles, :message, 10, "immudb.schema.NullableUint32"
      optional :commitLogMaxOpenedFiles, :message, 11, "immudb.schema.NullableUint32"
      optional :flushBufferSize, :message, 12, "immudb.schema.NullableUint32"
      optional :cleanupPercentage, :message, 13, "immudb.schema.NullableFloat"
    end
    add_message "immudb.schema.LoadDatabaseRequest" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.LoadDatabaseResponse" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.UnloadDatabaseRequest" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.UnloadDatabaseResponse" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.DeleteDatabaseRequest" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.DeleteDatabaseResponse" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.FlushIndexRequest" do
      optional :cleanupPercentage, :float, 1
      optional :synced, :bool, 2
    end
    add_message "immudb.schema.FlushIndexResponse" do
      optional :database, :string, 1
    end
    add_message "immudb.schema.Table" do
      optional :tableName, :string, 1
    end
    add_message "immudb.schema.SQLGetRequest" do
      optional :table, :string, 1
      repeated :pkValues, :message, 2, "immudb.schema.SQLValue"
      optional :atTx, :uint64, 3
      optional :sinceTx, :uint64, 4
    end
    add_message "immudb.schema.VerifiableSQLGetRequest" do
      optional :sqlGetRequest, :message, 1, "immudb.schema.SQLGetRequest"
      optional :proveSinceTx, :uint64, 2
    end
    add_message "immudb.schema.SQLEntry" do
      optional :tx, :uint64, 1
      optional :key, :bytes, 2
      optional :value, :bytes, 3
      optional :metadata, :message, 4, "immudb.schema.KVMetadata"
    end
    add_message "immudb.schema.VerifiableSQLEntry" do
      optional :sqlEntry, :message, 1, "immudb.schema.SQLEntry"
      optional :verifiableTx, :message, 2, "immudb.schema.VerifiableTx"
      optional :inclusionProof, :message, 3, "immudb.schema.InclusionProof"
      optional :DatabaseId, :uint32, 4
      optional :TableId, :uint32, 5
      repeated :PKIDs, :uint32, 16
      map :ColNamesById, :uint32, :string, 8
      map :ColIdsByName, :string, :uint32, 9
      map :ColTypesById, :uint32, :string, 10
      map :ColLenById, :uint32, :int32, 11
    end
    add_message "immudb.schema.UseDatabaseReply" do
      optional :token, :string, 1
    end
    add_message "immudb.schema.ChangePermissionRequest" do
      optional :action, :enum, 1, "immudb.schema.PermissionAction"
      optional :username, :string, 2
      optional :database, :string, 3
      optional :permission, :uint32, 4
    end
    add_message "immudb.schema.SetActiveUserRequest" do
      optional :active, :bool, 1
      optional :username, :string, 2
    end
    add_message "immudb.schema.DatabaseListResponse" do
      repeated :databases, :message, 1, "immudb.schema.Database"
    end
    add_message "immudb.schema.DatabaseListRequestV2" do
    end
    add_message "immudb.schema.DatabaseListResponseV2" do
      repeated :databases, :message, 1, "immudb.schema.DatabaseWithSettings"
    end
    add_message "immudb.schema.DatabaseWithSettings" do
      optional :name, :string, 1
      optional :settings, :message, 2, "immudb.schema.DatabaseNullableSettings"
      optional :loaded, :bool, 3
    end
    add_message "immudb.schema.Chunk" do
      optional :content, :bytes, 1
    end
    add_message "immudb.schema.UseSnapshotRequest" do
      optional :sinceTx, :uint64, 1
      optional :asBeforeTx, :uint64, 2
    end
    add_message "immudb.schema.SQLExecRequest" do
      optional :sql, :string, 1
      repeated :params, :message, 2, "immudb.schema.NamedParam"
      optional :noWait, :bool, 3
    end
    add_message "immudb.schema.SQLQueryRequest" do
      optional :sql, :string, 1
      repeated :params, :message, 2, "immudb.schema.NamedParam"
      optional :reuseSnapshot, :bool, 3
    end
    add_message "immudb.schema.NamedParam" do
      optional :name, :string, 1
      optional :value, :message, 2, "immudb.schema.SQLValue"
    end
    add_message "immudb.schema.SQLExecResult" do
      repeated :txs, :message, 5, "immudb.schema.CommittedSQLTx"
      optional :ongoingTx, :bool, 6
    end
    add_message "immudb.schema.CommittedSQLTx" do
      optional :header, :message, 1, "immudb.schema.TxHeader"
      optional :updatedRows, :uint32, 2
      map :lastInsertedPKs, :string, :message, 3, "immudb.schema.SQLValue"
      map :firstInsertedPKs, :string, :message, 4, "immudb.schema.SQLValue"
    end
    add_message "immudb.schema.SQLQueryResult" do
      repeated :columns, :message, 2, "immudb.schema.Column"
      repeated :rows, :message, 1, "immudb.schema.Row"
    end
    add_message "immudb.schema.Column" do
      optional :name, :string, 1
      optional :type, :string, 2
    end
    add_message "immudb.schema.Row" do
      repeated :columns, :string, 1
      repeated :values, :message, 2, "immudb.schema.SQLValue"
    end
    add_message "immudb.schema.SQLValue" do
      oneof :value do
        optional :null, :enum, 1, "google.protobuf.NullValue"
        optional :n, :int64, 2
        optional :s, :string, 3
        optional :b, :bool, 4
        optional :bs, :bytes, 5
        optional :ts, :int64, 6
      end
    end
    add_message "immudb.schema.NewTxRequest" do
      optional :mode, :enum, 1, "immudb.schema.TxMode"
    end
    add_message "immudb.schema.NewTxResponse" do
      optional :transactionID, :string, 1
    end
    add_message "immudb.schema.ErrorInfo" do
      optional :code, :string, 1
      optional :cause, :string, 2
    end
    add_message "immudb.schema.DebugInfo" do
      optional :stack, :string, 1
    end
    add_message "immudb.schema.RetryInfo" do
      optional :retry_delay, :int32, 1
    end
    add_enum "immudb.schema.EntryTypeAction" do
      value :EXCLUDE, 0
      value :ONLY_DIGEST, 1
      value :RAW_VALUE, 2
      value :RESOLVE, 3
    end
    add_enum "immudb.schema.PermissionAction" do
      value :GRANT, 0
      value :REVOKE, 1
    end
    add_enum "immudb.schema.TxMode" do
      value :ReadOnly, 0
      value :WriteOnly, 1
      value :ReadWrite, 2
    end
  end
end

module Immudb
  module Schema
    Key = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Key").msgclass
    Permission = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Permission").msgclass
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.User").msgclass
    UserList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UserList").msgclass
    CreateUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.CreateUserRequest").msgclass
    UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UserRequest").msgclass
    ChangePasswordRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ChangePasswordRequest").msgclass
    LoginRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.LoginRequest").msgclass
    LoginResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.LoginResponse").msgclass
    AuthConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.AuthConfig").msgclass
    MTLSConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.MTLSConfig").msgclass
    OpenSessionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.OpenSessionRequest").msgclass
    OpenSessionResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.OpenSessionResponse").msgclass
    Precondition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Precondition").msgclass
    Precondition::KeyMustExistPrecondition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Precondition.KeyMustExistPrecondition").msgclass
    Precondition::KeyMustNotExistPrecondition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Precondition.KeyMustNotExistPrecondition").msgclass
    Precondition::KeyNotModifiedAfterTXPrecondition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Precondition.KeyNotModifiedAfterTXPrecondition").msgclass
    KeyValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.KeyValue").msgclass
    Entry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Entry").msgclass
    Reference = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Reference").msgclass
    Op = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Op").msgclass
    ExecAllRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ExecAllRequest").msgclass
    Entries = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Entries").msgclass
    ZEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ZEntry").msgclass
    ZEntries = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ZEntries").msgclass
    ScanRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ScanRequest").msgclass
    KeyPrefix = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.KeyPrefix").msgclass
    EntryCount = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.EntryCount").msgclass
    Signature = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Signature").msgclass
    TxHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxHeader").msgclass
    TxMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxMetadata").msgclass
    LinearProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.LinearProof").msgclass
    DualProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DualProof").msgclass
    Tx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Tx").msgclass
    TxEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxEntry").msgclass
    KVMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.KVMetadata").msgclass
    Expiration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Expiration").msgclass
    VerifiableTx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableTx").msgclass
    VerifiableEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableEntry").msgclass
    InclusionProof = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.InclusionProof").msgclass
    SetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SetRequest").msgclass
    KeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.KeyRequest").msgclass
    KeyListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.KeyListRequest").msgclass
    DeleteKeysRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DeleteKeysRequest").msgclass
    VerifiableSetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableSetRequest").msgclass
    VerifiableGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableGetRequest").msgclass
    HealthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.HealthResponse").msgclass
    DatabaseHealthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseHealthResponse").msgclass
    ImmutableState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ImmutableState").msgclass
    ReferenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ReferenceRequest").msgclass
    VerifiableReferenceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableReferenceRequest").msgclass
    ZAddRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ZAddRequest").msgclass
    Score = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Score").msgclass
    ZScanRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ZScanRequest").msgclass
    HistoryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.HistoryRequest").msgclass
    VerifiableZAddRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableZAddRequest").msgclass
    TxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxRequest").msgclass
    EntriesSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.EntriesSpec").msgclass
    EntryTypeSpec = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.EntryTypeSpec").msgclass
    VerifiableTxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableTxRequest").msgclass
    TxScanRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxScanRequest").msgclass
    TxList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxList").msgclass
    ExportTxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ExportTxRequest").msgclass
    Database = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Database").msgclass
    DatabaseSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseSettings").msgclass
    CreateDatabaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.CreateDatabaseRequest").msgclass
    CreateDatabaseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.CreateDatabaseResponse").msgclass
    UpdateDatabaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UpdateDatabaseRequest").msgclass
    UpdateDatabaseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UpdateDatabaseResponse").msgclass
    DatabaseSettingsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseSettingsRequest").msgclass
    DatabaseSettingsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseSettingsResponse").msgclass
    NullableUint32 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NullableUint32").msgclass
    NullableUint64 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NullableUint64").msgclass
    NullableFloat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NullableFloat").msgclass
    NullableBool = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NullableBool").msgclass
    NullableString = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NullableString").msgclass
    DatabaseNullableSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseNullableSettings").msgclass
    ReplicationNullableSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ReplicationNullableSettings").msgclass
    IndexNullableSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.IndexNullableSettings").msgclass
    LoadDatabaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.LoadDatabaseRequest").msgclass
    LoadDatabaseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.LoadDatabaseResponse").msgclass
    UnloadDatabaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UnloadDatabaseRequest").msgclass
    UnloadDatabaseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UnloadDatabaseResponse").msgclass
    DeleteDatabaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DeleteDatabaseRequest").msgclass
    DeleteDatabaseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DeleteDatabaseResponse").msgclass
    FlushIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.FlushIndexRequest").msgclass
    FlushIndexResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.FlushIndexResponse").msgclass
    Table = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Table").msgclass
    SQLGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLGetRequest").msgclass
    VerifiableSQLGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableSQLGetRequest").msgclass
    SQLEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLEntry").msgclass
    VerifiableSQLEntry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.VerifiableSQLEntry").msgclass
    UseDatabaseReply = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UseDatabaseReply").msgclass
    ChangePermissionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ChangePermissionRequest").msgclass
    SetActiveUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SetActiveUserRequest").msgclass
    DatabaseListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseListResponse").msgclass
    DatabaseListRequestV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseListRequestV2").msgclass
    DatabaseListResponseV2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseListResponseV2").msgclass
    DatabaseWithSettings = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DatabaseWithSettings").msgclass
    Chunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Chunk").msgclass
    UseSnapshotRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.UseSnapshotRequest").msgclass
    SQLExecRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLExecRequest").msgclass
    SQLQueryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLQueryRequest").msgclass
    NamedParam = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NamedParam").msgclass
    SQLExecResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLExecResult").msgclass
    CommittedSQLTx = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.CommittedSQLTx").msgclass
    SQLQueryResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLQueryResult").msgclass
    Column = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Column").msgclass
    Row = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.Row").msgclass
    SQLValue = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.SQLValue").msgclass
    NewTxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NewTxRequest").msgclass
    NewTxResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.NewTxResponse").msgclass
    ErrorInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.ErrorInfo").msgclass
    DebugInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.DebugInfo").msgclass
    RetryInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.RetryInfo").msgclass
    EntryTypeAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.EntryTypeAction").enummodule
    PermissionAction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.PermissionAction").enummodule
    TxMode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("immudb.schema.TxMode").enummodule
  end
end
