# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: schema.proto for package 'immudb.schema'
# Original file comments:
#
# Copyright 2021 CodeNotary, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'grpc'
require_relative 'schema_pb'

module Immudb
  module Schema
    module ImmuService
      # immudb gRPC & REST service
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'immudb.schema.ImmuService'

        rpc :ListUsers, ::Google::Protobuf::Empty, ::Immudb::Schema::UserList
        rpc :CreateUser, ::Immudb::Schema::CreateUserRequest, ::Google::Protobuf::Empty
        rpc :ChangePassword, ::Immudb::Schema::ChangePasswordRequest, ::Google::Protobuf::Empty
        rpc :ChangePermission, ::Immudb::Schema::ChangePermissionRequest, ::Google::Protobuf::Empty
        rpc :SetActiveUser, ::Immudb::Schema::SetActiveUserRequest, ::Google::Protobuf::Empty
        rpc :UpdateAuthConfig, ::Immudb::Schema::AuthConfig, ::Google::Protobuf::Empty
        # DEPRECATED
        rpc :UpdateMTLSConfig, ::Immudb::Schema::MTLSConfig, ::Google::Protobuf::Empty
        # DEPRECATED
        rpc :OpenSession, ::Immudb::Schema::OpenSessionRequest, ::Immudb::Schema::OpenSessionResponse
        rpc :CloseSession, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :KeepAlive, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :NewTx, ::Immudb::Schema::NewTxRequest, ::Immudb::Schema::NewTxResponse
        rpc :Commit, ::Google::Protobuf::Empty, ::Immudb::Schema::CommittedSQLTx
        rpc :Rollback, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :TxSQLExec, ::Immudb::Schema::SQLExecRequest, ::Google::Protobuf::Empty
        rpc :TxSQLQuery, ::Immudb::Schema::SQLQueryRequest, ::Immudb::Schema::SQLQueryResult
        rpc :Login, ::Immudb::Schema::LoginRequest, ::Immudb::Schema::LoginResponse
        rpc :Logout, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        rpc :Set, ::Immudb::Schema::SetRequest, ::Immudb::Schema::TxHeader
        rpc :VerifiableSet, ::Immudb::Schema::VerifiableSetRequest, ::Immudb::Schema::VerifiableTx
        rpc :Get, ::Immudb::Schema::KeyRequest, ::Immudb::Schema::Entry
        rpc :VerifiableGet, ::Immudb::Schema::VerifiableGetRequest, ::Immudb::Schema::VerifiableEntry
        rpc :Delete, ::Immudb::Schema::DeleteKeysRequest, ::Immudb::Schema::TxHeader
        rpc :GetAll, ::Immudb::Schema::KeyListRequest, ::Immudb::Schema::Entries
        rpc :ExecAll, ::Immudb::Schema::ExecAllRequest, ::Immudb::Schema::TxHeader
        rpc :Scan, ::Immudb::Schema::ScanRequest, ::Immudb::Schema::Entries
        # NOT YET SUPPORTED
        rpc :Count, ::Immudb::Schema::KeyPrefix, ::Immudb::Schema::EntryCount
        # NOT YET SUPPORTED
        rpc :CountAll, ::Google::Protobuf::Empty, ::Immudb::Schema::EntryCount
        rpc :TxById, ::Immudb::Schema::TxRequest, ::Immudb::Schema::Tx
        rpc :VerifiableTxById, ::Immudb::Schema::VerifiableTxRequest, ::Immudb::Schema::VerifiableTx
        rpc :TxScan, ::Immudb::Schema::TxScanRequest, ::Immudb::Schema::TxList
        rpc :History, ::Immudb::Schema::HistoryRequest, ::Immudb::Schema::Entries
        rpc :Health, ::Google::Protobuf::Empty, ::Immudb::Schema::HealthResponse
        rpc :DatabaseHealth, ::Google::Protobuf::Empty, ::Immudb::Schema::DatabaseHealthResponse
        rpc :CurrentState, ::Google::Protobuf::Empty, ::Immudb::Schema::ImmutableState
        rpc :SetReference, ::Immudb::Schema::ReferenceRequest, ::Immudb::Schema::TxHeader
        rpc :VerifiableSetReference, ::Immudb::Schema::VerifiableReferenceRequest, ::Immudb::Schema::VerifiableTx
        rpc :ZAdd, ::Immudb::Schema::ZAddRequest, ::Immudb::Schema::TxHeader
        rpc :VerifiableZAdd, ::Immudb::Schema::VerifiableZAddRequest, ::Immudb::Schema::VerifiableTx
        rpc :ZScan, ::Immudb::Schema::ZScanRequest, ::Immudb::Schema::ZEntries
        # DEPRECATED: kept for backward compatibility
        rpc :CreateDatabase, ::Immudb::Schema::Database, ::Google::Protobuf::Empty
        rpc :CreateDatabaseWith, ::Immudb::Schema::DatabaseSettings, ::Google::Protobuf::Empty
        rpc :CreateDatabaseV2, ::Immudb::Schema::CreateDatabaseRequest, ::Immudb::Schema::CreateDatabaseResponse
        rpc :LoadDatabase, ::Immudb::Schema::LoadDatabaseRequest, ::Immudb::Schema::LoadDatabaseResponse
        rpc :UnloadDatabase, ::Immudb::Schema::UnloadDatabaseRequest, ::Immudb::Schema::UnloadDatabaseResponse
        rpc :DeleteDatabase, ::Immudb::Schema::DeleteDatabaseRequest, ::Immudb::Schema::DeleteDatabaseResponse
        rpc :DatabaseList, ::Google::Protobuf::Empty, ::Immudb::Schema::DatabaseListResponse
        rpc :DatabaseListV2, ::Immudb::Schema::DatabaseListRequestV2, ::Immudb::Schema::DatabaseListResponseV2
        rpc :UseDatabase, ::Immudb::Schema::Database, ::Immudb::Schema::UseDatabaseReply
        rpc :UpdateDatabase, ::Immudb::Schema::DatabaseSettings, ::Google::Protobuf::Empty
        rpc :UpdateDatabaseV2, ::Immudb::Schema::UpdateDatabaseRequest, ::Immudb::Schema::UpdateDatabaseResponse
        rpc :GetDatabaseSettings, ::Google::Protobuf::Empty, ::Immudb::Schema::DatabaseSettings
        rpc :GetDatabaseSettingsV2, ::Immudb::Schema::DatabaseSettingsRequest, ::Immudb::Schema::DatabaseSettingsResponse
        rpc :FlushIndex, ::Immudb::Schema::FlushIndexRequest, ::Immudb::Schema::FlushIndexResponse
        rpc :CompactIndex, ::Google::Protobuf::Empty, ::Google::Protobuf::Empty
        # Streams
        rpc :streamGet, ::Immudb::Schema::KeyRequest, stream(::Immudb::Schema::Chunk)
        rpc :streamSet, stream(::Immudb::Schema::Chunk), ::Immudb::Schema::TxHeader
        rpc :streamVerifiableGet, ::Immudb::Schema::VerifiableGetRequest, stream(::Immudb::Schema::Chunk)
        rpc :streamVerifiableSet, stream(::Immudb::Schema::Chunk), ::Immudb::Schema::VerifiableTx
        rpc :streamScan, ::Immudb::Schema::ScanRequest, stream(::Immudb::Schema::Chunk)
        rpc :streamZScan, ::Immudb::Schema::ZScanRequest, stream(::Immudb::Schema::Chunk)
        rpc :streamHistory, ::Immudb::Schema::HistoryRequest, stream(::Immudb::Schema::Chunk)
        rpc :streamExecAll, stream(::Immudb::Schema::Chunk), ::Immudb::Schema::TxHeader
        # Replication
        rpc :exportTx, ::Immudb::Schema::ExportTxRequest, stream(::Immudb::Schema::Chunk)
        rpc :replicateTx, stream(::Immudb::Schema::Chunk), ::Immudb::Schema::TxHeader
        rpc :SQLExec, ::Immudb::Schema::SQLExecRequest, ::Immudb::Schema::SQLExecResult
        rpc :SQLQuery, ::Immudb::Schema::SQLQueryRequest, ::Immudb::Schema::SQLQueryResult
        rpc :ListTables, ::Google::Protobuf::Empty, ::Immudb::Schema::SQLQueryResult
        rpc :DescribeTable, ::Immudb::Schema::Table, ::Immudb::Schema::SQLQueryResult
        rpc :VerifiableSQLGet, ::Immudb::Schema::VerifiableSQLGetRequest, ::Immudb::Schema::VerifiableSQLEntry
      end

      Stub = Service.rpc_stub_class
    end
  end
end
