name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.3
            immudb: 1.9.4
          - ruby: 3.2
            immudb: 1.5.0
          - ruby: 3.1
            immudb: 1.3.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          wget https://github.com/codenotary/immudb/releases/download/v$IMMUDB_VERSION/immudb-v$IMMUDB_VERSION-linux-amd64
          mv immudb-v$IMMUDB_VERSION-linux-amd64 immudb
          chmod +x immudb
          ./immudb -d
        env:
          IMMUDB_VERSION: ${{ matrix.immudb }}
      - run: bundle exec rake test
