name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.1
          immudb: 1.4.0
        - ruby: "3.0"
          immudb: 1.2.1
        - ruby: 2.7
          immudb: 1.1.0
        - ruby: 2.6
          immudb: 1.0.0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: |
        wget https://github.com/codenotary/immudb/releases/download/v$IMMUDB_VERSION/immudb-v$IMMUDB_VERSION-linux-amd64
        mv immudb-v$IMMUDB_VERSION-linux-amd64 immudb
        chmod +x immudb
        ./immudb -d
      env:
        IMMUDB_VERSION: ${{ matrix.immudb }}
    - run: bundle exec rake test
