name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - run: |
        wget https://github.com/codenotary/immudb/releases/download/v$IMMUDB_VERSION/immudb-v$IMMUDB_VERSION-linux-amd64
        mv immudb-v$IMMUDB_VERSION-linux-amd64 immudb
        chmod +x immudb
        ./immudb -d
      env:
        IMMUDB_VERSION: 1.3.0
    - run: bundle exec rake test
